repos:
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    - id: pyupgrade
      args: [--py37-plus]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear==21.9.1,
        flake8-logging-format==0.6.0,
        flake8-2020==1.6.0,
      ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.1.0]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
