name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
       node-version: '18.x'
    - name: Install dependencies
      run: python -m pip install -U jupyterlab~=4.0
    - name: Build the extension
      run: |
        jlpm
        jlpm run eslint:check
        python -m pip install yt
        python -m pip install .

        jupyter server extension list 2>&1 | grep -ie "widgyts.*OK"

        jupyter labextension list 2>&1 | grep -ie "@yt-project/yt-widgets.*OK"
        python -m jupyterlab.browser_check
