name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install flake8 pytest pytest-cov codecov
        if [ -f tests/requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Test with pytest and codecov
      run: |
        pytest --cov=widgyts --cov-report=xml widgyts
        coverage report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
